### ISSUE TITLE
output the document to a printer

### ISSUE THREAD

**Issue by ghost** [pulyaevskiy/quill-delta-dart#1]
Thanks for writing this plugin. Its going to be very popular i suspect.

This is tough one, but have your thought about if you will have printing out to a printer ?
From my research on it, its something that is not easy to do in flutter.
I think both android and IOS support printing a HTML document.  But i dont see how you quill plugin wil be able to do this inside flutter...

Like i said its a touch problem.

**Comment by pulyaevskiy** [comment]
In regards to this library, it's simply a port of official JS version, so it does only one thing - implements the data types and functionality like composing and transforming Deltas.

In regards to converting Deltas to other formats like HTML or Markdown: the task itself should be fairly straightforward, Delta is a very simple format. However there is one tricky part worth mentioning.

Delta does not come with concrete specification for how style attributes should be represented. Instead it's left up to the end user to come up with their own specification (end user here is basically a rich text editor).

What this means is that if we have 2 RTEs which both use Deltas as underlying data format their output is not guaranteed to be the same.

For instance, say I have a document containing string "Hello world" where the word "Hello" is styled as bold. One editor may define "bold" style as a Delta attribute with key `b`, and the other editor may use `bold` key. As a result two editors produce different Deltas for the same document.

This means that exporting Delta documents to other formats have to be specific to each editor.

Not sure if this answers your question though.

I also wanted to note that this library is not dependent on Flutter and not Flutter-specific at all. It is a generic Dart library which can be used on any supported platform, including web, Dart VM and Flutter of course.

**Comment by ghost** [comment]
@pulyaevskiy thankyou. It does answer it.
