### ISSUE TITLE
Different formats with quill.js

### ISSUE THREAD

**Issue by woodstream** [pulyaevskiy/quill-delta-dart#11]
This project use like this:
```
attributes: {block: 'quote }
```
and in quill.js use like this:
```
attributes: {blockquote: true}
```

**Comment by pulyaevskiy** [comment]
Delta format itself is agnostic of actual attribute names used by implementations. So there is nothing in this library that enforces any particular schema, the same as the official JS implementation of Deltas.

**Comment by cgestes** [comment]
(and as far I understand: Zefyr format is not made to be compatible with the quill one, but it should not be too hard to make a translator)
