### ISSUE TITLE
Double is not subtype of int

### ISSUE THREAD

**Issue by yamsergey** [pulyaevskiy/quill-delta-dart#18]
Hello, there is a possibility of a crash.

The default value for `length` is  `double.infinity`
https://github.com/pulyaevskiy/quill-delta-dart/blob/43d5e764fc2385d977fb84b4e2345898e786eab7/lib/quill_delta.dart#L642

Then we use the value within the `Operation`'s factory
https://github.com/pulyaevskiy/quill-delta-dart/blob/43d5e764fc2385d977fb84b4e2345898e786eab7/lib/quill_delta.dart#L671

But expected type is `int`
https://github.com/pulyaevskiy/quill-delta-dart/blob/43d5e764fc2385d977fb84b4e2345898e786eab7/lib/quill_delta.dart#L104

**Comment by pulyaevskiy** [comment]
Just an FYI this has been resolved in 3.0.0-nullsafety releases. Closing.
