### ISSUE TITLE
delta.toJson does not serialize Operation

### ISSUE THREAD

**Issue by a9a4k** [pulyaevskiy/quill-delta-dart#2]
![image](https://user-images.githubusercontent.com/6459157/46500191-e91d6700-c82a-11e8-9091-7670aceba876.png)

**Comment by pulyaevskiy** [comment]
That's correct. `Operation` provides it's own `toJson` method which is called by `jsonEncode`.

Is it not working for you?

**Comment by a9a4k** [comment]
From library user perspective it does not really make sense to do `delta.toJson().map((o) => o.toJson()).toList()`

**Comment by pulyaevskiy** [comment]
Not sure I’m following... you shouldn’t need to do all of that, you can simply just `jsonEncode(delta)`. Or are having issues with this?

**Comment by a9a4k** [comment]
Oh, sorry, I am new to dart :)

**Comment by pulyaevskiy** [comment]
Cool, no worries! Happy to help. Feel free to ask more questions.
